export const experienceItems = [
  {
    company: "Amazon",
    position: "Software Engineer Intern",
    location: "Vancouver, BC",
    date: "05/2026 - 08/2026",
    logo: "/img/logos/amazon.png",
    color: "#FF6200",
    link: "https://www.aboutamazon.com/",
    present: false,
    incoming: false,
  },
  {
    company: "Gem",
    position: "Software Engineer Intern",
    location: "San Francisco, CA",
    date: "01/2026 - 04/2026",
    logo: "/img/logos/gem.webp",
    color: "#0E61FF",
    link: "https://www.gem.com/",
    present: false,
    incoming: false,
  },
  {
    company: "Shopify",
    position: "Software Engineer Intern",
    location: "Toronto, ON",
    date: "01/2025 - 04/2025",
    logo: "/img/logos/shopify.svg",
    color: "#41623B",
    link: "https://www.shopify.com/",
    present: false,
    incoming: false,
  },
  {
    company: "Lawbrokr",
    position: "Software Developer Intern",
    location: "Toronto, ON",
    date: "05/2024 - 08/2024",
    logo: "/img/logos/lawbrokr.svg",
    color: "#B6B2D3",
    link: "https://lawbrokr.com",
    present: false,
    incoming: false,
  },
  {
    company: "BMO Financial Group",
    position: "Software Engineer Intern",
    location: "Toronto, ON",
    date: "09/2023 - 12/2023",
    logo: "/img/logos/bmo.svg",
    color: "#0A75BB",
    link: "https://bmo.com",
    present: false,
    incoming: false,
  },
  {
    company: "Brookfield",
    position: "Software Developer Intern",
    location: "Toronto, ON",
    date: "01/2023 - 04/2023",
    logo: "/img/logos/brookfield.webp",
    color: "#103557",
    link: "https://www.brookfield.com/",
    present: false,
    incoming: false,
  },
];

export const communityItems = [
  {
    company: "Wat Street",
    position: "Backend Developer",
    location: "Waterloo, ON",
    date: "01/2025 - 08/2025",
    logo: "/img/logos/watstreet.webp",
    color: "#1B1605",
    link: "https://watstreet.netlify.app/",
    present: false,
    incoming: false,
  },
  {
    company: "Hack the North",
    position: "Organizer",
    location: "Waterloo, ON",
    date: "03/2024 - 10/2024",
    logo: "/img/logos/hackthenorth.webp",
    color: "#141414",
    link: "https://hackthenorth.com",
    present: false,
    incoming: false,
  },
];

export const schoolItems = [
  {
    company: "University of Waterloo",
    position: "Computer Engineering",
    location: "Waterloo, ON",
    date: "09/2022 - 04/2027",
    logo: "/img/logos/uwaterloo.svg",
    color: "#666745",
    link: "https://uwaterloo.ca/engineering/",
    present: false,
    incoming: false,
  },
];
